print('周治成')
print(5)
print(9.556)
print(3 + 5)
print(3 * 5)
print(3**4444)
print('大幅度' + '奥术大师多')
print('gasldfi')
print('------1231231------')
temp = input('猜数字')
guess = int(temp)
if guess == 8:
    print('牛逼')
else:
    print('垃圾，我想的是8')
print('gg')